{{ if .Values.ingressRoute.enabled }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "name" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "name" . }}
          port: {{ .Values.service.port | default 80 }}

  tls:
    certResolver: tls

{{ end }}
