import { useState } from "react";
import { NextPage } from "next";
import Head from "next/head";
import { Rating } from "primereact/rating";
import { useTranslation } from "react-i18next";

export const Home: NextPage = () => {
  const { t } = useTranslation("common");
  const [stars, setStars] = useState<number>();
  return (
    <div className="flex flex-1 min-h-screen justify-content-center">
      <Head>
        <title>Prisme.ai Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex align-items-center justify-content-center flex-column">
        <h1 className="flex">{t("hello.world")}</h1>
        <div>
          <Rating
            value={stars}
            onChange={({ value = 0 }) => setStars(value || 0)}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
