apiVersion: v2
name: prismeai-apps
description: A Helm chart for Kubernetes

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

dependencies:
  - name: prismeai-functions
    version: 0.1.0
    condition: prismeai-functions.enabled

  - name: prismeai-nlu
    version: 0.1.0
    condition: prismeai-nlu.enabled

  - name: duckling
    version: 0.1.0
    condition: duckling.enabled

  - name: prismeai-crawler
    version: 0.1.0
    condition: prismeai-crawler.enabled

  - name: prismeai-searchengine
    version: 0.1.0
    condition: prismeai-searchengine.enabled

  - name: prismeai-llm
    version: 0.1.0
    condition: prismeai-llm.enabled


