version: "3"
services:
  mongo:
    image: mongo:4.0
    container_name: mongo_api
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: redis
    container_name: redis_api
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  runtime:
    working_dir: /www
    entrypoint: npm run dev --prefix=services/runtime
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-dependencies:latest
    volumes:
      - ./services/runtime:/www/services/runtime
      - ./data/models:/www/models
    depends_on:
      - redis
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      BROKER_HOST: redis://redis/10
      CONTEXTS_CACHE_HOST: redis://redis/0
      OPENAPI_FILEPATH: /www/specifications/swagger.yml
      WORKSPACES_STORAGE_TYPE: FILESYSTEM
      WORKSPACES_STORAGE_FILESYSTEM_DIRPATH: /www/models

  workspaces:
    working_dir: /www
    entrypoint: npm run dev --prefix=services/workspaces
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-dependencies:latest
    volumes:
      - ./services/workspaces:/www/services/workspaces
      - ./data/models:/www/models
    depends_on:
      - redis
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      BROKER_HOST: redis://redis/10
      OPENAPI_FILEPATH: /www/specifications/swagger.yml
      WORKSPACES_STORAGE_TYPE: FILESYSTEM
      WORKSPACES_STORAGE_FILESYSTEM_DIRPATH: /www/models

  gateway:
    working_dir: /www
    entrypoint: npm run dev --prefix=services/api-gateway
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-dependencies:latest
    volumes:
      - ./services/api-gateway:/www/services/api-gateway
    depends_on:
      - mongo
      - redis
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: development
      OPENAPI_FILEPATH: /www/specifications/swagger.yml
      USERS_STORAGE_HOST: mongodb://mongo/eda
      SESSIONS_STORAGE_HOST: redis://redis/2
      BROKER_HOST: redis://redis/10
  console:
    working_dir: /www
    entrypoint: npm run dev --prefix=services/console
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-dependencies:latest
    volumes:
      - ./services/console:/www/services/console
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_HOST: http://localhost:3001/v2
