enabled: false

splash:
  enabled: false
  resources:
    requests:
      memory: "1G"
      cpu: "500m"
    limits:
      memory: "4G"
      cpu: "1"

storage:
  cache:
    driver: redis
    # url:
    # url:
    #   valueFrom:
    #     secretKeyRef:
    #       name:
    #       key:

  documents:
    driver: elasticsearch
    url:
    # url:
    #   valueFrom:
    #     secretKeyRef:
    #       name:
    #       key:


# Additional envs
env: []

restartPolicy: Always

image:
  repository: registry.gitlab.com/gogowego-devsecops/dev/prisme.ai-crawler
  tag: latest
  pullPolicy: Always

replicaCount: 1

autorestart:
  enabled: false
  schedule: "0 3 * * *"

hpa:
  create: false
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: "0.70"
        # examples :
        # With a 50% CPU avg, will increase to 6 replicas if 4 replicas are using 70% cpu ( (70 / 50) * 4 = 5.6)
        # With a 50% CPU avg, will increase to 10 replicas if 7 replicas are using 70% cpu ( (70 / 50) * 7 = 9.8)

serviceAccount:
  create: false
  name:

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

ingressRoute:
  enabled: false
virtualService:
  enabled: false
  hosts: []
  gateways: []

resources:
  requests:
  limits:

nodeSelector: {}

tolerations: []

affinity:
  {}

volumes: []
volumeMounts: []