{{- range $ingress := .Values.ingresses }}

{{ $namespace := ($ingress.namespace | default $.Release.Namespace) }}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations: {{ toYaml $ingress.annotations | nindent 5 }}
  name: {{ $ingress.name }}
  namespace: {{ $namespace }}
spec:
  tls: {{ toYaml $ingress.tls | nindent 5 }}

  rules: {{ toYaml $ingress.rules | nindent 5 }}

{{- end }} # End of secrets loop
