version: '3'
services:
  mongo:
    image: mongo:4.0
    container_name: mongo_api
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ../../data/mongo:/data/db
  redis:
    image: redis
    container_name: redis_api
    restart: always
    volumes:
      - ../../data/redis:/data
    ports:
      - '6379:6379'
  api-gateway:
    entrypoint: npm start --prefix services/api-gateway
    restart: on-failure
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-api-gateway:latest
    depends_on:
      - mongo
      - redis
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: development
      OPENAPI_FILEPATH: /www/specifications/swagger.yml
      USERS_STORAGE_HOST: mongodb://mongo/users
      SESSIONS_STORAGE_HOST: redis://redis/2
      BROKER_HOST: redis://redis/10
      PERMISSIONS_STORAGE_HOST: mongodb://mongo/permissions
