endpoints:
  webhooks:
    path: '/v2/workspaces/*/webhooks/*'

  workspaces:
    path: '/v2/workspaces*'

  pages:
    path: '/v2/pages*'

  apps:
    path: '/v2/apps*'

  socket.io:
    path: '/socket.io*'

  events:
    path: '/v2/workspaces/*/events*'

  console:
    path: '*'
    hosts:
      - console.eda.prisme.ai

services:
  workspaces:
    url: ${WORKSPACES_API_URL:-http://workspaces:3002}
  runtime:
    url: ${RUNTIME_API_URL:-http://runtime:3003}
  events:
    url: ${EVENTS_API_URL:-http://events:3004}
  console:
    url: ${CONSOLE_API_URL:-http://console:3001}

pipelines:
  - name: runtime
    endpoints:
      - webhooks
    policies:
      - proxy:
          service: runtime

  - name: sockets
    endpoints:
      - socket.io
    policies:
      - authentication: {}
      - proxy:
          service: events
          websockets: true

  - name: events
    endpoints:
      - events
    policies:
      - authentication: {}
      - proxy:
          service: events

  - name: workspaces
    endpoints:
      - workspaces
      - apps
      - pages
    policies:
      - authentication: {}
      - proxy:
          service: workspaces

  - name: console
    endpoints:
      - console
    policies:
      - proxy:
          service: console
