endpoints:
  webhooks:
    path: '/v2/workspaces/:workspaceId/webhooks/*'
  test:
    path: '/v2/workspaces/:workspaceId/test/*'

  workspaces:
    path: '/v2/workspaces*'

  files:
    path: '/v2/files/*'
    methods:
      - get

  pages:
    path: '/v2/pages*'

  apps:
    path: '/v2/apps*'

  socket.io:
    path: '/socket.io*'

  events:
    paths:
      - '/v2/workspaces/:workspaceId/events'
      - '/v2/workspaces/:workspaceId/usage'
      - '/v2/workspaces/:workspaceId/search'
      - '/v2/search'

  console:
    path: '*'
    hosts:
      - console.eda.prisme.ai

services:
  workspaces:
    url: ${WORKSPACES_API_URL:-http://workspaces:3002}
  runtime:
    url: ${RUNTIME_API_URL:-http://runtime:3003}
  events:
    url: ${EVENTS_API_URL:-http://events:3004}
  console:
    url: ${CONSOLE_API_URL:-http://console:3001}

pipelines:
  - name: runtime
    endpoints:
      - webhooks
      - test
    policies:
      - rateLimit:
          key: userId
          window: 60
          limit: 30
          name: webhooks
      - rateLimit:
          key: workspaceId
          window: 3600
          limit: 2000
          name: webhooks
      - authentication:
          optional: true
          csrf:
            validateToken: true
      - proxy:
          service: runtime

  - name: sockets
    endpoints:
      - socket.io
    policies:
      - authentication:
          optional: true
      - proxy:
          service: events
          websockets: true

  - name: events
    endpoints:
      - events
    policies:
      - match:
          paths:
            - '/v2/workspaces/:workspaceId/search'
            - '/v2/workspaces/:workspaceId/events'
            - '/v2/workspaces/:workspaceId/usage'
        rateLimit:
          key: userId
          window: 60
          limit: 20
          name: searchEvents
      - authentication:
          optional: true
          csrf:
            validateToken: true
      - proxy:
          service: events

  - name: files
    endpoints:
      - files
    policies:
      - authentication:
          optional: true
          csrf:
            validateToken: true
      - proxy:
          service: workspaces

  - name: workspaces
    endpoints:
      - workspaces
      - apps
    policies:
      - authentication:
          allowApiKeyOnly: true
          csrf:
            validateToken: true
      - match:
          paths:
            - '/v2/workspaces/:workspaceId/files'
          methods:
            - POST
        rateLimit:
          key: userId
          window: 60
          limit: 50
          name: uploadFile
      - match:
          paths:
            - '/v2/workspaces/'
          methods:
            - POST
        rateLimit:
          key: userId
          window: 60
          limit: 3
          name: createWorkspace
      - match:
          paths:
            - '/v2/workspaces/import'
            - '/v2/workspaces/:workspaceId/import'
            - '/v2/workspaces/:workspaceId/versions/:versionId/pull'
            - '/v2/workspaces/:workspaceId/versions/:versionId/duplicate'
        rateLimit:
          key: userId
          window: 60
          limit: 3
          name: importWorkspace
      - proxy:
          service: workspaces

  - name: pages
    endpoints:
      - pages
    policies:
      - authentication:
          optional: true
          csrf:
            includeToken: true
      - proxy:
          service: workspaces

  - name: console
    endpoints:
      - console
    policies:
      - proxy:
          service: console
