endpoints:
  webhooks:
    path: "/v2/workspaces/*/webhooks/*"

  workspaces:
    path: "/v2/workspaces*"

  apps:
    path: "/v2/apps*"

  console:
    path: "*"
    hosts:
      - console.eda.prisme.ai

services:
  workspaces:
    url: "http://workspaces:3002"
  runtime:
    url: "http://runtime:3003"
  events:
    url: "http://events:3002"
  console:
    url: "http://console:3001"

pipelines:
  - name: runtime
    endpoints:
      - webhooks
    policies:
      - authentication: {}
      - proxy:
          service: runtime

  - name: workspaces
    endpoints:
      - workspaces
      - apps
    policies:
      - authentication: {}
      - proxy:
          service: workspaces

  - name: console
    endpoints:
      - console
    policies:
      - proxy:
          service: console
