endpoints:
  webhooks:
    path: '/v2/workspaces/*/webhooks/*'
  test:
    path: '/v2/workspaces/*/test/*'

  workspaces:
    path: '/v2/workspaces*'

  files:
    path: '/v2/files/*'
    methods:
      - get

  pages:
    path: '/v2/pages*'

  apps:
    path: '/v2/apps*'

  socket.io:
    path: '/socket.io*'

  events:
    paths:
      - '/v2/workspaces/*/events'
      - '/v2/workspaces/*/usage'
      - '/v2/workspaces/*/search'
      - '/v2/search'

  console:
    path: '*'
    hosts:
      - console.eda.prisme.ai

services:
  workspaces:
    url: ${WORKSPACES_API_URL:-http://workspaces:3002}
  runtime:
    url: ${RUNTIME_API_URL:-http://runtime:3003}
  events:
    url: ${EVENTS_API_URL:-http://events:3004}
  console:
    url: ${CONSOLE_API_URL:-http://console:3001}

pipelines:
  - name: runtime
    endpoints:
      - webhooks
      - test
    policies:
      - proxy:
          service: runtime

  - name: sockets
    endpoints:
      - socket.io
    policies:
      - authentication: {}
      - proxy:
          service: events
          websockets: true

  - name: events
    endpoints:
      - events
    policies:
      - proxy:
          service: events

  - name: files
    endpoints:
      - files
    policies:
      - proxy:
          service: workspaces

  - name: workspaces
    endpoints:
      - workspaces
      - apps
    policies:
      - authentication:
          allowApiKeyOnly: true
      - proxy:
          service: workspaces

  - name: pages
    endpoints:
      - pages
    policies:
      - authentication:
          optional: true
      - proxy:
          service: workspaces

  - name: console
    endpoints:
      - console
    policies:
      - proxy:
          service: console
