enabled: true

# Additional envs
env:
  - name: PORT
    value: "80"

storage:
  permissions:
    driver:
    url:

######################################
#### Infrastructure configuration ####
######################################
cache:
  contexts:
    driver: redis
    url:
    password:

global:
  repository:
    host:
    username:
    token:

  broker:
    driver: ""
    url: ""
    password: ""
    maxLen: "1000"

  storage:
    permissions:
      driver:
      url:

    workspaces:
      driver: S3_LIKE

      s3_like_accessKey: ""
      s3_like_baseUrl: ""
      s3_like_bucketName: ""
      s3_like_endpoint: ""
      s3_like_secretKey: ""

image:
  repository: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-runtime
  tag: latest
  pullPolicy: Always

replicaCount: 1

autorestart:
  enabled: true
  schedule: "0 3 * * *"

hpa:
  create: false
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: "0.70"
          # examples :
          # With a 50% CPU avg, will increase to 6 replicas if 4 replicas are using 70% cpu ( (70 / 50) * 4 = 5.6)
          # With a 50% CPU avg, will increase to 10 replicas if 7 replicas are using 70% cpu ( (70 / 50) * 7 = 9.8)

service:
  type: NodePort
  port: 80

serviceAccount:
  create: false
  name:

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

resources:
  requests:
  limits:

nodeSelector: {}

tolerations: []

affinity:
  {}

  # Only set the MONGODB_CA_FILE env variable if the files is provided

prometheus:
  serviceMonitor:
    enabled: false
    metricRelabelings: []
    relabelings: []

ingressRoute:
  enabled: false
  host: ""

virtualService:
  enabled: false
  hosts: []
  gateways: []

networkPolicy:
  enabled: false
  from: []

volumes: []
volumeMounts: []
