enabled: false

redis:
  maxmemory: '4000mb'

# Additional envs
env: []

image:
  repository: redis/redis-stack-server
  tag: 7.0.6-RC9
  pullPolicy: Always

replicaCount: 1

autorestart:
  enabled: false
  schedule: "0 3 * * *"

hpa:
  create: false
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: "0.70"
          # examples :
          # With a 50% CPU avg, will increase to 6 replicas if 4 replicas are using 70% cpu ( (70 / 50) * 4 = 5.6)
          # With a 50% CPU avg, will increase to 10 replicas if 7 replicas are using 70% cpu ( (70 / 50) * 7 = 9.8)

service:
  type: NodePort
  port: 6379

serviceAccount:
  create: false
  name:

resources:
  requests:
    memory: '4000mi'
  limits:

nodeSelector: {}

tolerations: []

affinity: {}

virtualService:
  enabled: false
  hosts: []
  gateways: []

networkPolicy:
  enabled: false
  from: []

statefulset: false
