{{ if .Values.virtualService.enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  hosts:
    {{ toYaml .Values.virtualService.hosts | nindent 5 }}
  gateways:
    {{ toYaml .Values.virtualService.gateways | nindent 5 }}
  http:
  - route:
    - destination:
        host: {{ include "name" . }}

{{ end }}
