apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector: {{ include "selectorLabels" . | nindent 4 }}

  {{ if .Values.service.extraSpecs }}
  {{- toYaml .Values.service.extraSpecs | nindent 2 }}
  {{ end }}
