version: '3'
services:
  console:
    entrypoint: npm start  --prefix services/pages
    restart: on-failure
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-pages:latest
    ports:
      - '3000:3100'
    environment:
      API_HOST: http://localhost:3001/v2
