{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {{ include "selectorLabels" . | nindent 7 }}
  ingress:
    - from: {{ toYaml .Values.networkPolicy.from | nindent 9 }}
      ports:
        - port: {{ .Values.service.port }}
{{- end }}
