apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  master.conf: |
    maxmemory {{ .Values.redis.maxmemory | default "4000mb" }}
    maxmemory-policy noeviction
    maxclients 20000
    timeout 300
    dbfilename dump.rdb
    dir /data
    appendonly yes
    save ""
  # slave.conf: |
  #   slaveof redis-stack-0.redis-service.redis 6379
  #   maxmemory 1000mb
  #   maxmemory-policy allkeys-lru
  #   maxclients 20000
  #   timeout 300
  #   dir /data
  #   appendonly yes
  #   save ""
