version: "3"
services:
  console:
    entrypoint: npm start  --prefix services/console
    image: registry.gitlab.com/prisme.ai/prisme.ai/prisme.ai-console:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_HOST: http://localhost:3001/v2
